version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_SHEETS_CREDENTIALS_FILE=credentials.json
      - GOOGLE_SHEETS_SPREADSHEET_ID=${GOOGLE_SHEETS_SPREADSHEET_ID}
      - GOOGLE_SHEETS_RANGE_NAME=${GOOGLE_SHEETS_RANGE_NAME}
      - WOOCOMMERCE_URL=${WOOCOMMERCE_URL}
      - WOOCOMMERCE_CONSUMER_KEY=${WOOCOMMERCE_CONSUMER_KEY}
      - WOOCOMMERCE_CONSUMER_SECRET=${WOOCOMMERCE_CONSUMER_SECRET}
      - KEEPA_API_KEY=${KEEPA_API_KEY}
      - KEEPA_DOMAIN=${KEEPA_DOMAIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ENGINE_ID=${OPENAI_ENGINE_ID}
    env_file:
      - .env